### ISSUE TITLE
Error on tutorial startup.

### ISSUE THREAD

**Issue by ghost** [maxogden/elementary-electron#4]
I've got an error, when trying to start tutorial.

$ elementary-electron
C:\Users\рорао\AppData\Roaming\npm\node_modules\elementary-electron\node_modules\adventure\lib\menu.js:51
    process.stdin.setRawMode(true);
                  ^

TypeError: process.stdin.setRawMode is not a function
    at module.exports (C:\Users\рорао\AppData\Roaming\npm\node_modules\elementary-electron\node_modules\adventure\lib\menu.js:51:19)
    at Shop.showMenu (C:\Users\рорао\AppData\Roaming\npm\node_modules\elementary-electron\node_modules\adventure\index.js:267:16)
    at Shop.execute (C:\Users\рорао\AppData\Roaming\npm\node_modules\elementary-electron\node_modules\adventure\index.js:131:14)
    at Object.<anonymous> (C:\Users\рорао\AppData\Roaming\npm\node_modules\elementary-electron\cli.js:21:6)
    at Module._compile (module.js:409:26)
    at Object.Module._extensions..js (module.js:416:10)
    at Module.load (module.js:343:32)
    at Function.Module._load (module.js:300:12)
    at Function.Module.runMain (module.js:441:10)
    at startup (node.js:134:18)

**Comment by ghost** [comment]
And another error when selecting a lesson.

$ elementary-electron select 2
C:\Users\рорао\AppData\Roaming\npm\node_modules\elementary-electron\node_modules\adventure\index.js:248
    var p = adv.fn();
               ^

TypeError: Cannot read property 'fn' of undefined
    at Shop.select (C:\Users\рорао\AppData\Roaming\npm\node_modules\elementary-electron\node_modules\adventure\index.js:248:16)
    at Shop.execute (C:\Users\рорао\AppData\Roaming\npm\node_modules\elementary-electron\node_modules\adventure\index.js:97:14)
    at Object.<anonymous> (C:\Users\рорао\AppData\Roaming\npm\node_modules\elementary-electron\cli.js:21:6)
    at Module._compile (module.js:409:26)
    at Object.Module._extensions..js (module.js:416:10)
    at Module.load (module.js:343:32)
    at Function.Module._load (module.js:300:12)
    at Function.Module.runMain (module.js:441:10)
    at startup (node.js:134:18)
    at node.js:962:3

**Comment by ghost** [comment]
Solved.

$ node -p -e "Boolean(process.stdout.isTTY)" 
If its true, try to use cmd.

**Comment by martinheidegger** [comment]
The latest version of elementary-electron should have this problem solved. Would you mind to retry it?
